### PR TITLE
Fixes the circular JSON TypeError

### PR DESCRIPTION
**Pull request by ThinkTankShark**

### CODE REVIEW

**Comment by krisk** [comment]
Thanks @ThinkTankShark, but unfortunately, this cannot be merged. We need an alternative solution that doesn't use external dependencies.

**Comment by ThinkTankShark** [comment]
Hi @krisk. Thanks for the response. I didn't realize that I left that external dependency in the code.... It was unnecessary and I removed it. Please let me know if you I need to do anything else to help out. Great module, super useful.

**Comment by jeffal** [comment]
Will this fix be added now that the external dependency has been removed?

**Comment by valera-rozuvan** [comment]
@ThinkTankShark Merge conflicts ...

**Comment by ThinkTankShark** [comment]
Thank you @valera-rozuvan! Fixed. 👍

**Comment by ksloan** [comment]
Can we merge this please? :)

**Comment by grajagandev** [comment]
Would you be interested in software that automatically finds TypeErrors caused by corner cases like circular structures? I am building [Fuzz Stati0n](https://fuzzstati0n.com/?id=197) to do that (free for OSS) - please take a look and consider signing up for our newsletter to keep in touch.

**Comment by Neill83** [comment]
hi @krisk,

could you merge this PR please?

Regards

**Comment by ksloan** [comment]
@krisk any updates on this?

**Comment by ThinkTankShark** [comment]
@krisk Would you please let us know if this is going to get **approved** / merged anytime soon or should we close it? I would be more than happy to fix the branch conflicts if it's approved. Thanks

**Comment by ksloan** [comment]
@krisk 🙏

**Comment by ksloan** [comment]
just another monthly checkin on this issue

**Comment by ksloan** [comment]
April check-in, how's this going?

**Comment by ksloan** [comment]
May-be?

**Comment by ThinkTankShark** [comment]
@krisk Can you please update everyone on this PR? Appreciate it.

**Comment by ksloan** [comment]
@krisk

**Comment by ksloan** [comment]
I missed July... my bad. Can we please get this merged for August?!

**Comment by krisk** [comment]
Well, this was embarrassing on my part. My apologies on the unforgivably long delay, @ThinkTankShark!

There were several conflicts, as the library had been updated a while back, so I incorporated your codebase instead (as merging was slightly nightmarish). Credit given 100% to you though, and noted in [v3.3.1 release notes](https://github.com/krisk/Fuse/blob/master/CHANGELOG.md#version-331)

**Pull request closed without merging**
