### PR TITLE
Improve score algorithm when there are exact matches or pattern if found multiple times

### PR DESCRIPTION
**Pull request by eduardo-matos**
There are two major improvements on this PR.

1. When there are exact matches, the score increases significantly.
2. If a given pattern is "found" once in an item and twice on another, the the one with more matches has its score increased.

All previous behaviors continue to exist and they're the default ones.

If you want to privilege exact matches, then set the option `privilegeExactMatch` to `true`.
If you want weight the matches (more matcher = more relevant), then set the option `scoreStrategy` to `"weighted"`.

### CODE REVIEW

**Comment by krisk** [comment]
Thanks for the pull request. I like what you're suggesting, but with one concern: I'm of the opinion that an **exact match should be indicated with a score of zero**. As really the score is the [Levenshtein distance](http://en.wikipedia.org/wiki/Levenshtein_distance)

**Comment by eduardo-matos** [comment]
The problem with an exact match having a zero score is that a non-exact match may have the same score. The idea behind giving it a better score is to set it appart from all non-exact matches.

**Comment by kkragenbrink** [comment]
I would very much like to see this PR completed, whether at 0 or greater.   The features in it would be of use to me.

**Comment by krisk** [comment]
This should be addressed with version 2.0.0

**Pull request closed without merging**
