### PR TITLE
Add a getDocs method

### PR DESCRIPTION
**Pull request by dburdan**
Simply adds a `getDocs()` method to export the docs of an existing Fuse instance.

### CODE REVIEW

**Comment by krisk** [comment]
Trying to understand the need for this. Given that the entire collection would be passed in during instantiation, what is the need to expose it? Would you not already have access to it?

**Comment by dburdan** [comment]
When some computationally expensive docs are dynamically added overtime, it was helpful to have access to the already processed docs (and index) to avoid recomputing them to reinstantiate an instance. The processed docs can always be stored elsewhere locally, but given the Fuse instance held them it seemed like a good fit.

Possibly import/export methods:
- `Fuse.setCollection(docs, index)` -> `Fuse.import(docs, index)`
- `Fuse.getIndex(): FuseIndex<T>` -> `Fuse.export(): { docs: T[], index: FuseIndex<T> }`

Would love your thoughts. If this doesn't seem like a common use case I can keep it in my fork.

**Comment by krisk** [comment]
Thanks for the explanation!

I think it's worth clarifying that `docs` is never mutated by Fuse.js; rather the library takes the input docs and creates an entirely new index from them, which is what is used for searching. Ergo, returning `docs`, in my mind, is redundant, as they already exist in userland 😄

**Comment by dburdan** [comment]
Totally makes sense; appreciate your feedback. Given this hasn't been a PR before, I imagine my usage is very atypical.

**Comment by GMartigny** [comment]
Just to add a real use-case for a `getDocs` method.

I'm using Fuse.js in a Vue instance. I first initialise a Fuse instance in the component setup, then I make an XHR to my API on mounted and `setCollection` with the result. Finally, I compute the filtered list by calling `search`. But when the search is empty, I want to return the whole collection. This is where I have to retrieve "docs" from the Fuse instance.

I could have a separate copy of the collection, but it would be quite redundant.

Anyway, `fuse.getIndex().docs` works fine.

**Pull request closed without merging**
