### PR TITLE
Filter out empty values from tokens array

### LINKED ISSUE #131: Token Seperation Issue
I have discovered an issue when `tokenize` and `matchAllTokens` is enabled. When you search for `white ` (with a trailing whitespace), the `tokens` are `['white', '']`. This causes fuse to return no results due to one empty token. Would removing empty tokens as below be a fix for this?

```
var tokens = pattern.split(options.tokenSeparator).filter(function(token){
    return token !== '';
})
```

### PR DESCRIPTION
**Pull request by jwmann**
This fixes #131 where if `tokenize` and `matchAllTokens` is enabled, the `tokens` array would have an empty value at the end of the array, if you use the same tokenSeparator at the end of the search pattern.
e.g.: `"My String"` vs `"My String "` using ` ` as a separator.

Fuse will return empty results if an empty string/value is passed as tokens.

This fix passes all current tests.
I attempted to write a specific test for this case but I can't access the tokens array from results.

### CODE REVIEW

**Comment by jwmann** [comment]
Dammit TravisCI, my build didn't error, your npm install failed..

**Comment by bendaenen** [comment]
This fix is not yet released?

**Comment by jwmann** [comment]
Nope, he just closed the Pull Request. #FeelsBad

**Comment by Tsourdox** [comment]
Why was this closed? This bug is really annoying =(

**Pull request closed without merging**
