### PR TITLE
fix: ensure string before checking for blank

### PR DESCRIPTION
**Pull request by mrdivyansh**
The code crashes if `value` is an object.

Screen Shot 2020-10-29 at 12 20 00 PM

https://jsfiddle.net/hza6d3ge/

### CODE REVIEW

**Comment by joaovbibiano** [comment]
This solution will care about Dates and Object? I think it is not. We can make a JSON.stringify if it is an object

**Comment by joaovbibiano** [comment]
> The code crashes if `value` is an object.
> 
> Screen Shot 2020-10-29 at 12 20 00 PM
> 
> https://jsfiddle.net/hza6d3ge/

This solution will care about Dates and Object? I think it is not. We can make a JSON.stringify if it is an object

**Comment by davidkhierl** [comment]
_ping_

**Comment by bernhardc** [comment]
Is there any way to help moving this forward?

**Comment by mrdivyansh** [comment]
I am closing this PR as @krisk has already taken the change as part of https://github.com/krisk/Fuse/commit/1de1dffa3f16992e21d817370e2b5d9611d3ad6d.

Thanks @krisk 

cc @johnnynomad @davidkhierl @joaobibiano

**Pull request closed without merging**
