### PR TITLE
feat(scoring): field length norm weight

### PR DESCRIPTION
**Pull request by adlerfaulkner**
Add advanced config option fieldNormWeight to allow for
customizability in how much field-length norm effects scores.

### CODE REVIEW

**Comment by adlerfaulkner** [comment]
Hello!

For my use case I felt like the field-length norm factor was boosting short results too much compared to other good results, but I didn't want to turn it off completely so I added an option to tone down (or up) the field-length norm function. 

The previous field-length norm function is `1/srqt(x)` where x is the number of words in the field. This PR changes that function to `1/x^(0.5*fieldNormWeight)`.  `fieldNormWeight` defaults to 1, making the functions equivalent. However, changing `fieldNormWeight` to 0.5 produces a "smoother" curve, lessening the effects of field-length norm on the score of long fields.

**Comment by krisk** [comment]
This is excellent. Thanks!

**Comment by krisk** [comment]
mm had to do a manual merge. Closed by a9e00804497a1bfd7a94040520417825c085c945

**Comment by krisk** [comment]
Can you create a separate PR to add the necessary documentation? Thanks!

**Comment by adlerfaulkner** [comment]
Yes, will get to that tomorrow :)

**Comment by adlerfaulkner** [comment]
@krisk https://github.com/krisk/Fuse/pull/603

**Pull request closed without merging**
