### PR TITLE
[RFT] Switch bundler to Rollup

### LINKED ISSUE #262: ES6 Modules
Is there a real reason, why we don't ship ES6 modules?
I would like to see an additional export at this point, I would also do a PR, if wished and needed.

Regards, 
   Johann

### PR DESCRIPTION
**Pull request by cshoredaniel**
**NB** This is only _lightly_ tested (`yarn test`).  Testing and comments are recommended before inclusion.

* It allows us to ship ES6 modules (Closes #262)
* It's faster (and in the opinion of this committer, cleaner)
* While we're at it normalize bundle filenames
  - Make fuse.js the unminified version
  - Make fuse.min.js the minified version (sort of breaking change)
* Add hidden sourcemaps for minified versions (no sourceMap comment)
* Add external sourcemaps for unminified version, except fuse.dev.js
  which keeps its inline sourcemap

Signed-off-by: Daniel F. Dickinson <cshored@thecshore.com>

### CODE REVIEW

**Comment by krisk** [comment]
Hey @cshoredaniel - I'm still somewhat torn about the _fuse_ to _fuse.min_ rename, as that is breaking change (which you have also noted above). I do agree that at some point, we should just do it though.

I'm going to pull this change and test + think about it. Thanks!

**Comment by cshoredaniel** [comment]
Yeah I dithered about the .min change too.  I'm wondering if this + the other breaking changes in the beta warrant a deprecation on the npm package and rename to e.g. fusejs or so?

**Comment by cshoredaniel** [comment]
It occurs to me to ask if there should be some tests of the different types of packages (e.g. umd vs. es6) and/or some test using jsdom and a script tag for the browser use of umd?

**Comment by krisk** [comment]
> ... I'm wondering if this + the other breaking changes in the beta warrant a deprecation on the npm package and rename to e.g. fusejs or so?

I'd rather not create another package. I think the semantic bump in major version to v5 is already somewhat indicative of the potential for breaking changes (in this case, there already are breaking changes as you've noted).

(Tangentially - I recall that when I had initially built this, I did have a `.min`, but at some point, long ago, it was changed via a pull request)._

**Comment by cshoredaniel** [comment]
@krisk I agree on the major version thing.  I did a quick search old PR and think the problem was a hotfix for webpack adding eval for it's dev tools thing.

**Comment by cshoredaniel** [comment]
I've got some other things I'm working on right now but I'll see about adding appropriate tests for the different bundles at some point reasonably soon-ish.

**Comment by sidvishnoi** [comment]
Can we avoid running Babel on ESM builds? Given ESM is supported in browsers that support most other ES6 features, we should be able to reduce the bundle size there by avoiding Babel. 
Not sure how to prevent running a plugin based on `output.format` though.

**Comment by KonradHoeffner** [comment]
ES6 works now, thanks! See https://github.com/krisk/Fuse/issues/262#issuecomment-601593475.

**Comment by cshoredaniel** [comment]
On 2020-03-20 4:49 a.m., Sid Vishnoi wrote:
>
> Can we avoid running Babel on ESM builds? Given ESM is supported in 
> browsers that support most other ES6 features, we should be able to 
> reduce the bundle size there by avoiding Babel.
> Not sure how to prevent running a plugin based on |output.format| though.
>
I thought about that but I didn't see a way to do it, but your message 
prompted me to think about again, and I realized that Rollup uses an 
array for it's config so that you can essentially do two separate sets 
of build and output with the same config, so it might actually be 
possible.  I'll give it a try in a bit. Thanks for reminding me.

**Comment by krisk** [comment]
Hey - I took a stab at this, as I wanted to simplify the architecture while also cleaning up the types. Check this out #367

**Comment by cshoredaniel** [comment]
Hi, it'll probably be a day or two before I can look at #367 in detail, but it looks like this has inspired some great changes.  Most excellent ;-)

**Comment by cshoredaniel** [comment]
Once I've got some time from other things I'll have to browse this and the README and such to get a better idea of what's changed, but **wow!**
Hope you're able to keep up the good work -- If I had money I'd sponsor you (it's a long story), but in the meantime I'll at least contribute when and what I can.

**Pull request closed without merging**
