### PR TITLE
Made a proper comment style

### PR DESCRIPTION
**Pull request by hacktivist123**
Properly comment out a code block

### CODE REVIEW

**Comment by krisk** [comment]
Can probably actually just erase that code :)

**Comment by hacktivist123** [comment]
Oh! I’ll do just that right away.

**Comment by hacktivist123** [comment]
Hey, @krisk done what you suggested already!

**Comment by krisk** [comment]
Looks like this was already removed in the "next" branch before the merge to master. Will close this. Thanks for working on it!

**Pull request closed without merging**
