### PR TITLE
enable esm transpilation - fixes IE11 compatibility.

### PR DESCRIPTION
**Pull request by avilv**

### CODE REVIEW

**Comment by klarstrup** [comment]
4 releases since this PR went up, any feedback @krisk?

**Comment by avengerx** [comment]
Isn't this just a config setting and pull request sets this IE11 compatibiliuty "on by default"?

Just wondering if this should be a documentation issue or considered a bug.

**Comment by radhikagupta5** [comment]
Any update on when this would be merged and released?

**Comment by krisk** [comment]
Could you not simply pull in `fuse.common.js`? See [here](https://fusejs.io/getting-started/different-builds.html)

**Comment by avilv** [comment]
> Could you not simply use `fuse.common.js`? See [here](https://fusejs.io/getting-started/different-builds.html)

this would work for old webpack / browserify, but not for anything modern that uses the ESM output (i.e, webpack2, angular cli, react etc. )

**Comment by cironunes** [comment]
It would be awesome to have a way to use the latest Fuse in IE11. Any chance we can get it?

**Comment by Qrymy** [comment]
@krisk 
Hi, I'm using fuse.js, and great library, thanks!
And I'm facing ie11 build problem. I know I should use `fuse.common.js`, however I'm using with Next.js x TypeScript.
So there is no type definitions in `fuse.common.js`, So I suggest you two ideas.

1. Merge this pr
This is most easiest way, but bundle size will be larger than now, and ie11 will be disappear soon (1 year or more...).

2. Create esm for ie11
This way is so clever, [react-hook-form](https://react-hook-form.com/) is doing. For example,
```
import Fuse from 'fuse.js' // this is support except ie11
import Fuse from 'fuse.js/dist/fuse.ie11' this is support also ie11
```
If you adopt this way, normal bundle size will be same, and if ie11 disappear, you should remove as soon as possible.

If you think this way is good, I will make pr.

Thanks.

**Comment by mcrawshaw** [comment]
@krisk will @Qrymy suggestion work?

**Comment by Reached** [comment]
Could we get this merged in by any chance? :)

**Pull request closed without merging**
