### PR TITLE
[eval unsafe] fix build production only!! [urgent]

### PR DESCRIPTION
**Pull request by salvoravida**
eval( ) problem on production!! csp unsafe

### CODE REVIEW

**Comment by JCKodel** [comment]
StencilJS is complaining about it also:
```
[ WARN  ]  Bundling Warning
           Use of eval is strongly discouraged, as it poses security risks and may cause issues with minification
```

**Comment by johannwagner** [comment]
Is there a real reason, why you want to use the minified version? If you use a production ready toolchain, your toolchain will include and minify this in your build.

**Comment by salvoravida** [comment]
no the only reason is that in 3.4.0 the NON min version is a DEV version with eval( ....
and if you are on a server with CSP that does not allow eval unsafe.eval all is broken!!

i think you shoud release in dist/ only PRODUCTION env code, min and non min version

**Comment by salvoravida** [comment]
https://github.com/krisk/Fuse/blob/master/dist/fuse.js#L114

**Comment by johannwagner** [comment]
So, your proposed fix is a hotfix and not a correct fix. 
You may want to look at #280, where an similar issue is described.

**Comment by JCKodel** [comment]
StencilJS is complaining about 3.4 (it was not in 3.3). I don't know if it
imports dev or production, and I don't really care. For me, just stopped
working.

[ WARN  ]  Bundling Warning
           Use of eval is strongly discouraged, as it poses security risks
and may cause issues with minification

**Comment by salvoravida** [comment]
i think you are missing the point.
dist/fuse.js is built in DEV MOE and is exported from package JSON -> main: "dist/fuse.js"
dist/fuse.min.js is bult in PROD mode but is NOT exported anyware. 

ok?

i'm pushing a FULL fix to webpack.config.js 
give me 5 minutes

**Comment by johannwagner** [comment]
I totally got your point.

I just wanted to point out, that it is not the solution to use the minified version, otherwise you will kill tree shaking for other users. You have to fix the non minifed build, this also should be production ready, because it is in the dist folder.

**Comment by salvoravida** [comment]
@johannwagner see now. thanks

**Comment by krisk** [comment]
Taking a look at this now. Thanks for flagging. Broken behavior right now.

**Comment by salvoravida** [comment]
thank you ! all is working now!

**Pull request merged**
